### ISSUE TITLE
Create script to change fog darkness depending on world height

### ISSUE THREAD

**Issue by JLastig** [Het-verborgen-oog/Game#128]
Script using the Cart's world height to change the Post Exposure of the Volume on the Main Camera (shown in image below)

![Image](https://user-images.githubusercontent.com/45848255/208410129-f04b85a0-f68d-401f-a298-7464eb5a98ab.png)

**Comment by RobinvHoof** [comment]
After an attempt on implementing it turns out this is very intensive for the game to run, as adjusting the Post Exposure on every frame requires the rendering engine to rerender the entire effect every time on every frame (causing heavy performance issues)
