### ISSUE TITLE
Create Design: Islands for Deep Sea

### ISSUE THREAD

**Issue by Rick-jpg** [Het-verborgen-oog/Game#60]

**Comment by NathanThus** [comment]
@Rick-jpg Waarom staat er 13 uur op het design?

**Comment by NathanThus** [comment]
![Image](https://user-images.githubusercontent.com/99728206/205022296-de5cf47d-a8cd-48ef-95fa-c59fb6a7092f.png)



![Image](https://user-images.githubusercontent.com/99728206/205022353-97c14b62-d6de-4d74-a11b-9fe1877b1df9.png)

**Comment by NathanThus** [comment]
![Image](https://user-images.githubusercontent.com/99728206/205024959-cd0acfc8-63fc-41d3-a131-de07824c0ca7.png)



![Image](https://user-images.githubusercontent.com/99728206/205024984-d65c3997-18d9-400e-b2fb-0a0709999c35.png)

**Comment by NathanThus** [comment]
![Image](https://user-images.githubusercontent.com/99728206/205048641-448e423d-edb9-46b3-8b56-9eb749bc8334.png)

**Comment by NathanThus** [comment]
@Rick-jpg Denk dat dit wel goed is?
